title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://jasondl.ee" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jasondlee
github_username:  jasondlee

# Build settings
theme: minima
gems:
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-asciidoc
  - jekyll/tagging

#markdown: kramdown
highlighter: rouge
#kramdown:
#  input: GFM
#  syntax_highlighter_opts:
#    default_lang: java
#    css_class   : 'syntax'

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=rouge
    - rouge-css=style

tag_page_layout: tag
tag_page_dir: tags

excerpt_separator: "// more"
permalink: /:year/:title:output_ext
paginate: 10
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - myblog
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
