---
title: "Easily Switching JDKs"
date: 2019-08-26
tags: [JDK, Bash]
type: post
author: Jason Lee
status: published
---

Development environments can get fairly complex, and making sure you're using the right version of some library or another
can be annoying on the best of days. I have a situation like that where my "day job" requires (still, and hopefully not
for much longer) JDK 8, but my side projects, learning efforts, etc. can use a more modern version.

Years ago, https://twitter.com/headius[Charles Nutter] shared a
https://gist.github.com/happygiraffe/148320/aab71e624f4db87694717fef561e89c72b1acfc2[shell script] he uses to switch JDKs.
I've been happily using it, but I've made some minor tweaks, so I thought I'd share
my version here in case it helps someone (and make it easier for me to find in the future ;).

*UPDATE:* It seems the original author is https://twitter.com/nicksieger/status/1166070669244796929[Nick Sieger]. Thanks
to you as well, Nick, for a great little utility!

// more

The two primary changes in my script versus Charles' is that I try to set JDKS_ROOT if it's not already set, and I try
to filter out "false" JDK entries (where the Ubuntu packages, for example, seem to like to create symlinks). I have not
tested these changes to make sure I haven't broken MacOS support, however, so if you're on a Mac and this doesn't work
correctly, please let me know. :)

Without further ado:

[source, bash]
-----
{#include ./script.bash /}
-----

To use this, add the following to your Bash profile:

[source,bash]
-----
source /path/to/pickjdk.sh
-----

Restart your shell (or source the file directly), and you can do this:

[source,bash]
-----
$ pickjdk
 1) java-11-openjdk-amd64 < CURRENT
 2) oracle-java8-jdk-amd64
 3) None
Choose one of the above [1-3]:
-----

Make your selection, and you're all set. It's awesome.
