---
title: "NetBeans Program Update - Feb 2009"
date: 2009-02-11
tags: [NetBeans]
type: post
link: /:year/:slug
status: published
---
= NetBeans Program Update - Feb 2009
Jason Lee
2009-02-11

Are you a NetBeans user?  Are you wondering what's going to happen to your IDE of choice given the recent Sun restructuring?  The NetBeans Dream Team Call with Matt Thompson the new Sun NetBeans Director, which starts at 10:00am CST *today* (I just learned about it too) should answer some of your questions.  Here are the details:

NetBeans Program Update - Feb 2009
----------------------------------
with Matt Thompson (the new NetBeans Director + Developer Cloud Tools Engineering)
SLIDES ARE https://java-champions.dev.java.net/pdfs/nbroadahead.pdf[HERE]
WED Feb 11th at 0800am Pacific; 11am US East Coast; 5 pm Europe
US Toll Free Dial-in Number: *866-803-2141*
CALL ID: 5121251
Participant Code: GO Here: *http://nbdt-feb09.eventbrite.com/*
We will be recording this call for later playback on this event page.
Tentative AGENDA:
* Intros and NetBeans team changes + Sun's Cloud Initiative – Matt Thompson (15 minutes)
* Discuss future topics about upcoming NetBeans Technical Calls -- What does the dreamteam want to talk about first...open mic vote if necessary w/Matt... (15min)
* Open Communication Q & A What is on your Mind?? – All (30 minutes)
