---
title: "Another NetBeans Update"
date: 2009-02-19
tags: [Java, NetBeans]
author: Jason Lee
type: post
status: published
---
= Another NetBeans Update

Since the announcement in the recent layoffs at Sun on how the NetBeans team was affected, there's been much concern over the health of the project.  I'm not on the NetBeans team (I'm just a big Finkel fan! ;) so I can't say for certain what's going on, but it seems to me that Sun is still committed to the platform.  Evidence of that comes in the form of an email I got today about the upcoming 6.7 release.  Here is the email:
// more

[quote]
----
For those of you who have been following the NetBeans release train, you may be puzzled by the version number switch in our upcoming milestone release, from NetBeans 7.0 to NetBeans 6.7.

To get innovation and quality improvements out to the community faster, and to have the NetBeans IDE be better aligned with the release schedules of other technologies that it supports, we have decided to concentrate on a series of smaller releases rather than the traditional two big releases per year.

With this new focus on smaller releases, we renamed the next release according to our numbering guidelines:

Point versions (for example, 6.0 to 6.1) indicate less change, and API compatibility.

A whole number version jump (for example, 5.0 to 6.0) reflects major feature changes within the NetBeans IDE, and possible API incompatibilities.

These guidelines communicate, in a general way, the level of change to expect in the NetBeans IDE, and we always want to meet these expectations. At this time, NetBeans 6.7 is the best possible product that we can deliver by June 2009. We are confident that this is the right move for the NetBeans IDE and for our users who have come to expect top quality releases.

And why are we skipping a version between 6.5 and 6.7? Well, there are negative associations with the number 6.6...6. Though we appreciate a good laugh, this is not the permanent association we want for the IDE.

NetBeans 6.7 is scheduled for release in June 2009. The main features are Maven and http://kenai.com/[Kenai] integration, and there are many smaller features that you can read about on the http://wiki.netbeans.org/NewAndNoteWorthy[New and Noteworthy] page. Java EE 6 support is planned for a future release. *NetBeans 6.7 Milestone 2 is due out next week*. We encourage you to download the release when it becomes available and to give us your feedback.

Thank you for your continued support of the NetBeans IDE.
----

== The NetBeans Team

While you're all capable of reading things for yourself, I'd like to highlight two things.  First is the rationale behind the version number: "And why are we skipping a version between 6.5 and 6.7? Well, there are negative associations with the number 6.6...6. Though we appreciate a good laugh, this is not the permanent association we want for the IDE."  Not in any way important, but I thought that it was hilarious. :)

On a more serious note, here are some of the highlights (for me) of the major changes coming in 6.7 (or full details, click the New and Noteworthy link in the email above):

* Importing plugins from previous release into new one
* Maven project support
** Compile On Save support
** Improved, more powerful Add Dependency dialog with as-you-type searching in Maven repositories...
** Better POM xml editing support like support for generating profiles, dependencies via Alt + Insert shortcut
* PHP
** Generating Getters and Setters Improved
** SFTP support added
** Parameter Info
** Code completion for constructors
** Marking returns
** Go to type for class members - improved
** SQL code completion in the PHP editor
** Marking occurrences improved
* JavaScript - Support for JavaScript 1.7 (More information)

Lots of neat stuff, but the one I'm most excited about is that first one: importing plugins.  That I had to re-install all of my plugins.  Since I don't have to do that anymore, I think I'm going to go grab M1, even though M2 is coming out tomorrow.  I love the bleeding edge... :)

I didn't see any mention of Python support, though.  I hope I just missed that...
