---
title: "Leveraging Identity with GlassFish and MySQL"
date: 2009-02-11
tags: [GlassFish, identity, MySQL]
type: post
link: /:year/:slug
status: published
---
= Leveraging Identity with GlassFish and MySQL
Jason Lee
2009-02-11

Late last year and early this year, I spent a great deal of time to author/edit a white paper detailing the deployment of Sun Identity Manager using GlassFish and MySQL.  The paper, with additional input from Ed Ort, Suveen Nadipalli and John Clingan, gives a brief introduction to what identity management is and why you'd want it, then covers the whats, hows, and whys of MySQL and GlassFish installation, the installation and configuration of Sun Identity Manager, tuning the system, and ends with a quick look at the total cost of ownership.  I think we put together a very nice paper on a very interesting and oft-overlooked piece of enterprise data management.  If you're interested in reading more, you can click http://www.sun.com/offers/details/LeveragingIdentityGlassFish.html[here] for the download page.
