title: Steeplesoft
author: Jason Lee
local_tz: America/Chicago
interpolate: false

asciidoctor:
  :compact: true
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-' 

scss:
  :line_numbers: true
  :style: :expanded
# if no profile is specified, the first with a deploy config is selected
profiles:
  development:
    deploy:
      dummy:
  production:
    base_url: http://blogs.steeplesoft.com
    #disqus_developer: false
    #google_analytics: UA-33133481-1

    # TODO enable once not dependent on system binaries
    minify: true

    deploy:
      host: steeplesoft.com
      path: /home/tlh/steeplesoft.com/beta

