title: Steeplesoft
author: Jason Lee
local_tz: America/Chicago
interpolate: false
uncommitted: true
disqus: steeplesoft
base_url: http://localhost:1234

asciidoctor:
  :compact: true
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-' 

scss:
  :line_numbers: true
  :style: :expanded
# if no profile is specified, the first with a deploy config is selected
profiles:
  development:
    minify: false
    disqus_developer: true
    dev: true
    deploy:
      dummy:
  production:
    base_url: http://blogs.steeplesoft.com
    #disqus_developer: false
    google_analytics: UA-1091049-1

    # TODO enable once not dependent on system binaries
    minify: true

    deploy:
      host: tlh@steeplesoft.com
      path: /home/tlh/steeplesoft.com/awestruct

