title: Steeplesoft
author: Jason Lee
local_tz: America/Chicago
interpolate: false
disqus: steeplesoft
base_url: http://localhost:4242
minify: true

asciidoctor:
  :compact: true
  :eruby: erubis
  :attributes:
    source-highlighter: coderay
    coderay-css: style
    idprefix: ''
    idseparator: '-' 

minify_html_opts:
    remove_intertag_spaces: true
    compress_js: true

scss:
  :line_numbers: true
  :style: :expanded
# if no profile is specified, the first with a deploy config is selected
profiles:
  development:
    minify: false
    asciidoctor:
        :compact: false
    disqus_developer: true
    dev: true
    deploy:
      dummy:
  production:
    base_url: http://blogs.steeplesoft.com
    disqus_developer: false
    google_analytics: UA-1091049-1

    # TODO enable once not dependent on system binaries

    deploy:
      uncommitted: true
      host: tlh@steeplesoft.com
      path: /home/tlh/steeplesoft.com/awestruct

