---
title: "GlassFish Roadmap"
date: 2010-03-26
tags: [GlassFish]
type: post
link: /:year/:slug
status: published
---
= GlassFish Roadmap
Jason Lee
2010-03-26

There has been a lot of speculation and concern about the fate of GlassFish after the Oracle acquisition.  Yesterday, though, we were able to unveil the official roadmap for GlassFish, and I think it looks very promising.  In short, not much is going to change with regard to the open source side of things, though there are some changes on the commercially supported offering, which is not unexpected.  Some of the highlights include:

* GlassFish 3.0.1 - 2010
** Branding and patches</li>
** Multi-lingual release</li>
** Value-added features for Oracle GlassFish Server</li>
** Base interop w/Oracle Middleware products</li>
* GlassFish 3.1 - 2010
** Centralized administration of cluster</li>
** HA/state replication</li>
** Value-added features like Coherence Support</li>
* GlassFish 3.2 - 2011
** Improved cluster/HA admin</li>
** Better integration with Oracle Identity Management</li>
** Virtualization support</li>
** Some Java EE 6 spec updates plus some Java EE 7 EA specs</li>
* GlassFish 4
** Common server platform - shared best-of-breed with WebLogic Server</li>
** Java EE 7</li>

For a more complete picture, see the slide deck http://glassfish.org/roadmap[here].
