---
title: "JavaOne 2008: Day 4"
date: 2008-05-10
tags: [Java, JavaOne]
type: post
link: /:year/:slug
status: published
---
= JavaOne 2008: Day 4
Jason Lee
2008-05-10

Like every other day at JavaOne, Friday started with a general session, this one led by James Gosling.  Unlike other days, though, today would be a short one.
// more

I was a bit late to session, so I missed what Schwartz, Green, and Melissinos were doing on stage with Gosling, but there was a large piece of artwork handed over.  Who knows.  Well, apparently over 1,000 people, if I had to guess, do know, but I don't. :)  The session was better attended than I expected, being Friday and all.  The room was dark, but it was half full, if not three quarters full.

Gosling spent his time highlighting interesting Java technologies, some of which we've seen all week, such as the Sentilla devices and the LiveScribe Pulse Smartpen.  I won't go into details (for that, see Joe's http://www.theserverside.com/news/thread.tss?thread_id=49339[post] on The Server Side), but this thing is extremely cool.

The demo that really wowed me was Tor Norbye's demo of NetBeans 6.1's JavaScript support.  He demonstrated how the enhancements that went into making NetBeans 6 a great Ruby IDE had been adapted to make NetBeans a great JavaScript IDE, offering things like code completion and error highlighting.  Tor also showed how NetBeans will inform you when a function you're about to call is not compatible with certain browsers.  The coolest part of the whole demo, though, was the debugger.  I think most serious web developers know about Firebug, but this debugger, which is a Firefox plugin (with support for other, more monopolistic and less functional browsers coming soon) allows the developer to set a breakpoint in NetBeans, hit the page in Firefox, then have the breakpoint tripped in the IDE, allowing for things like inspection of local variables, etc.  In some ways, it seems very much like Firebug's debugger, but the integration with the IDE, allowing for live editing of the code (if I recall correctly), is extremely cool.

Gosling also spent some time on the jMonkeyEngine, which is an engine to make writing games in Java easier.  It allows the game designer to "focus on making great games" according to Chris Melissinos.  I'm not much into writing games, but I have to admit that it was an impressive piece of work.  It looked very professional.  What surprised me is the <strike>foolishness</strike> bravery of the presenters, as they were demoing a game based on the engine by playing against people in the UK which meant that *they were depending on the Moscone internet link*.  Luckily, it was pretty flawless.

Gosling also showed, with the help of Ken Russell and Sven Gothel, a JOGL application running on a phone, using an http://www.nvidia.com/object/apx_2500.html[Nvidia APX 2500] processor.  It was a very slick demo.  The audio was a bit choppy -- they were pegging the CPU, which they admitted they needed to fix -- but it's a good sign that mobile Java is making good strides as well.

I didn't get to see everything Gosling showed, as I had to step out and head to the All Java Web Tier EG meeting.  We had JSF, Servlet and Portlet people all in the same room, discussing some overlapping functionality and where it all went.  I may cover the details in another post, but I will say this about the meeting:  it was quite a collection of some REALLY smart people:  Ed, Roger, Hani, Greg Wilkins, and a host of others.  For all the gritching some people have about the JCP, it was impressive and reassuring to see some of the sharpest minds in the industry discussing -- and sometimes arguing over -- the best way to extend the various specs.  It's clear that it's not an ivory tower approach, as the needs/demands of the various user communities were clearly presented, and very forcefully defended.

So that's it for JavaOne 2008.  It was a great week, if not very tiring, and often like drinking from a fire hose.  From fairly early mornings to (usually) very late nights, the conference will keep you going, constantly throwing information at you.  Even at the roughly 3 bazillion parties, meant to entertain, technology was never far from the minds and mouths of the attendees.  JavaOne is certainly something every serious Java developer should experience.  And, as silly as this may sound, the rah rah hype of the marketing side worked:  I'm genuinely _more_ excited about being a Java developer than I was.  After being exposed to all of the great things going on in the non-web areas of Java, my list of things to learn and experiment with has gone from hard to manage to nearly impossible.  And that's fine by me. :)
