name: Publish Blog

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@master
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: mvn clean generate-resources

      - name: Publish
        uses: up9cloud/action-rsync@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USER: ${{ secrets.SSH_USER }}
          KEY: ${{secrets.SSH_KEY}}
          SOURCE: ./output/*
          TARGET: ${{ secrets.SSH_DIR }}
#      - name: Publish
#        uses: nogsantos/scp-deploy@master
#        with:
#          src: ./output/*
#          host: ${{ secrets.SSH_HOST }}
#          remote: ${{ secrets.SSH_DIR }}
#          port: ${{ secrets.SSH_PORT }}
#          user: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_KEY }}
